# Generated by Django 5.0.7 on 2024-09-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('prompt', models.TextField()),
                ('education', models.TextField(null=True)),
                ('experience', models.TextField(null=True)),
                ('languages', models.TextField()),
                ('references', models.TextField()),
            ],
        ),
    ]
